#!/usr/bin/env node

const fs = require('fs');

// 获取提交消息
const commitMsgFile = process.argv[2];
const message = fs.readFileSync(commitMsgFile, 'utf-8');

// 允许changeset和版本更新提交通过
if (message.match(/^chore: (add changeset|version packages)/)) {
  process.exit(0);
}

// 检查是否是通过我们的工具提交的
if (process.env.ARBANK_COMMIT !== 'true') {
  console.log('❌ 请使用 \'pnpm commit\' 命令来提交代码');
  process.exit(1);
} 